### ISSUE TITLE
Expand documentation on stdweb::event_loop()

### ISSUE THREAD

**Issue by Shnatsel** [koute/stdweb#11]
`You should call this before returning from main(), otherwise bad things will happen.` is not sufficient documentation, because it raises the following questions:

1. What if I include the code compiled into asm.js as part of a larger codebase and `main()` never gets called? Do I still have to call this, and when?

1. What does this do, exactly? If I'm converting parts of a large JS codebase into Rust and I call this, what changes should I expect? (Also featuring: "What if I do not want Rust code to react to events? Do I still have to call it?", "I have not called it and have not observed any ill effects. What do?", etc.)

1. How does calling this interact with `-s NO_EXIT_RUNTIME=1` flag passed to emcc?

Looking at the implementation revealed nothing other than that it seems to be some kind of call required for any Emscripten code. If that is true, a link to emscripten documentation would solve point 2.

**Comment by koute** [comment]
Yes, those are very good questions indeed! I do have to confess that I don't really know the answers to them myself though... (:

I'm not sure if it's possible to not call `main()` **if** you include the file somewhere; (As it - you add a `<script>` tag which requires it.) as far as I know it's not possible, although I might be wrong.

Basically, from what I've observed - you should always put it at the end of `main()` before returning, and if you don't then I guess part of the runtime will deinitialize itself (since you've returned from `main()`) and things will be broken?

**Comment by koute** [comment]
Calling `stdweb::event_loop` is now unnecessary when compiling with `cargo-web`, and I've updated the documentation to reflect that, so - closing.

**Comment by Shnatsel** [comment]
> I'm not sure if it's possible to not call main() if you include the file somewhere

I've actually managed to do that by hooking up the resulting asmjs file to a large JS codebase with its own build system that eventually rolls everything up in a single file and minifies it (which is a fairly typical procedure for JS). 

To circumvent that I've left main() empty and added an init() method that I've always called explicitly.
