### ISSUE TITLE
TypeError: Module.STDWEB_PRIVATE is undefined

### ISSUE THREAD

**Issue by ndarilek** [koute/stdweb#163]
I'm attempting to use Yew to build an HTML interface for my app. I get this error in the call to `Yew::initialize();`.

When I tracked this to `Yew::initialize()`, I set about attempting to discover why this works fine on a small test crate, but fails on a much larger one. My test crate only depends on Yew, which depends on stdweb transitively. My actual crate links in SpatiaLite, SQLite, and a bunch of larger libraries.

I modified `Yew::initialize()` to look as follows:

```
pub fn initialize() {
    stdweb::initialize();
    println!("Initializing JS");
    js! {
        console.log("Here");
```

In my test crate, where everything works, both lines print. In my larger crate, `console.log` doesn't trigger.

Is it possible that, in a larger crate, JS is still loading or streaming wasm is still compiling, and `STDWEB_PRIVATE` hasn't been defined when `stdweb::initialize()` finishes? Then the `js!` macro is called, expecting this module to be defined, only it isn't?

I don't yet know if I'm open sourcing the larger crate, but I'll happily privately make available a JS/wasm bundle if that would help with development. I could share the entire source privately, but getting all the libraries vendored is a bit hacky.

Thanks.

**Comment by koute** [comment]
How are you compiling your code? Are you using `cargo-web`? For which target are you compiling? Is it the same on every one?

If you're using an Emscripten-based target make sure you're using Emcripten which is automatically downloaded by `cargo-web`, or a newer version if you're using your own.

**Comment by ndarilek** [comment]
Using cargo-web, wasm32-unknown-emscripten with a system-provided
toolchain, version 1.37.36. I haven't tested asmjs--I'm using a number
of natively-compiled dependencies, so I worry that using asmjs would
ultimately be too slow.

**Comment by koute** [comment]
Hmm... your Emscripten should be new enough to work. (Too old Emscripten versions apparently don't work https://github.com/koute/stdweb/issues/95)

Are you perhaps using a conditional `[target.'cfg(...)'.dependencies]` anywhere? (https://github.com/koute/stdweb/issues/135)

You could also try to use the Emscripten built into `cargo-web`, and if that fails perhaps you could try to produce a minmal example which reproduces the problem.

**Comment by ndarilek** [comment]
Yup, #135 was it. Thanks, I checked open issues before filing this one, didn't think to check closed issues, nor did I suspect this was a cargo-web issue. It can be hard to know whether a given issue is in Yue, Stdweb, etc. I wonder if it might be more helpful to leave issues like #135 open for folks like me who hit it but don't know that it's a build tool bug?

Thanks!

**Comment by nstoddard** [comment]
I'm seeing a similar issue, but I'm not using `cargo-web`. Everything works if I call `stdweb::initialize()` from my main crate, but it gives an error about `STDWEB_PRIVATE` being undefined if `stdweb::initialize()` is only called by the library. Should I make a new issue for this or should this issue be reopened?

(I'm not using `cargo-web` because I'm using emscripten's `GLFW` implementation.)

**Comment by koute** [comment]
@nstoddard If you're not using `cargo-web` then calling `stdweb::initialize` is required before calling *anything* else. This behavior is expected and there isn't anything we can do about it.

`stdweb` needs extra runtime written in JS; you can either let `cargo-web` automatically take care of it for you, or you need to initialize it yourself with `stdweb::initialize`.

(Well, technically it might be possible to have `stdweb::initialize` called automatically even without `cargo-web` - I haven't checked if it'd work - but then it'd require Rust nightly as the required feature is not stabilized IIRC.)

If your project builds when built manually but fails when building with `cargo-web` then feel free to open a new issue for that, as something like that definitely shouldn't happen. (Just be sure to first try out the `--use-system-emscripten` option to check if the issue is perhaps due to that particular Emscripten version which `cargo-web` uses.)

**Comment by nstoddard** [comment]
@koute Thanks, I'd thought `stdweb::initialize` only had to be called before using the `js!` macro.

It looks like my issue with `cargo web` was due to a conflict with the version of `emscripten` I installed manually, because it was still trying to use the old `~/.emscripten` config file.
