### ISSUE TITLE
docs: how to include a npm/javascript dependency

### ISSUE THREAD

**Issue by vitiral** [koute/stdweb#167]
I think it would be helpful to add a snippet in the README on how to include an npm dependency and the absolute basics of using it.

Thanks!

**Comment by Pauan** [comment]
I'm not sure if it's even possible to include npm dependencies right now. There is a lot of work being done on the [rust-wasm group](https://github.com/rust-lang-nursery/rust-wasm) (and [the `wasm-pack` tool](https://github.com/ashleygwilliams/wasm-pack)) to allow that to happen, but I don't think any of that work is integrated into stdweb.

**Comment by vitiral** [comment]
OK, cool. Thanks!

Feel free to close or keep open as a reference for others.

**Comment by vitiral** [comment]
@Pauan any idea how to do the following:

- include a javascript file and call a function?
- include a raw text/json file?

Thanks!

**Comment by vitiral** [comment]
Wow, I answered the first one by just playing around

In `static/hello.js`

```
function hello(name) {
    alert( `Hello ${name}!` );
}
```

In `static/index.html`:
```
...
<script src="hello.js"></script>
...
```

Then literally anywhere in rust:
```
js! {
    hello("bob");
    hello("World");
}
```

**Comment by vitiral** [comment]
Oh, sorry -- I actually want it to be read at runtime. I want my CLI to be able to inject a json file containing the data for a static web page.

Do you know how to do that?

I've finally found _a method_, although it's not very good.

        console.log("Getting text");
        var request = new XMLHttpRequest();
        request.open('GET', 'text.txt', false);
        request.send();
        var text = request.responseText;
        console.log("TEXT:\n" + text)

However, it prints all sorts of junk to the console:

```
Getting text
index.html:12:9
TEXT:
Hello, I am text.
My name is Bob?

index.html:17:9: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
index.html:14:8: XML Parsing Error: syntax error
Location: file:///home/garrett/notes/js/play_html/text.txt
Line Number 1, Column 1:
```

**Comment by vitiral** [comment]
So I'm reconsidering... I can probably just kick off the request in `create` and not do anything until the data is gotten. That's _probably_ the right way to do this :smile:

**Comment by Pauan** [comment]
@vitiral The only (supported) way to load files at runtime in JavaScript is to use async APIs.

The recommendation is to use [the `fetch` API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), which is supported in all modern browsers. If you need to support older browsers you can use [this `fetch` polyfill](https://github.com/github/fetch).

In order to use `fetch` inside of Rust, you would do this:

First, enable the `experimental_features_which_may_break_on_minor_version_bumps` feature for stdweb:

```
[dependencies]
stdweb = { version = "0.4.3", features = ["experimental_features_which_may_break_on_minor_version_bumps"] }
```

As its name suggests, there might be breaking changes at any time.

Then you need to create a Rust wrapper around the `fetch` API, like this:

```rust
use stdweb::PromiseFuture;

fn fetch(url: &str) -> PromiseFuture<String> {
    js!( return fetch(@{url}).then(function (response) { return response.text(); }); ).try_into().unwrap()
}
```

Now you can use normal Rust Future APIs (and `PromiseFuture::spawn` to actually spawn the Future):

```rust
fn main() {
    PromiseFuture::spawn(
        fetch("./path/to/file.json")
            .map(|json| {
                // parse and use JSON in here
            })
            .map_err(|e| console!(error, e))
    );
}
```

Right now stdweb supports `futures` version `0.1`, but I'm working on adding in support for `futures` version `0.2`

**Comment by Pauan** [comment]
stdweb now has support for Futures 0.2

The only real difference is that now you must use `PromiseFuture::spawn_local` and `PromiseFuture::print_error_panic`, like this:

```rust
fn main() {
    PromiseFuture::spawn_local(
        fetch("./path/to/file.json")
            .map(|json| {
                // parse and use JSON in here
            })
            .map_err(PromiseFuture::print_error_panic)
    );
}
```
