### ISSUE TITLE
If I were to add DOMContentLoaded, where would I add it?

### ISSUE THREAD

**Issue by rickycodes** [koute/stdweb#169]
would it make sense to add this in `/src/webapi/events/dom.rs`
or should there be a new file for DOM mutation events?

**Comment by teovoinea** [comment]
My say is to put it in `/src/webapi/events/dom.rs` as opposed to creating a new file for DOM mutation events. According to [this MDN guide](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events#Mutation_events_list), DOM mutation events are being deprecated for [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) because of performance issues and (lack of?) cross browser support.

**Comment by rickycodes** [comment]
I realized that I could use `ReadyStateChangeEvent`, so am not sure if this is worth adding as that API and `MutationObserver` seem like fine alternatives?

**Comment by koute** [comment]
Yeah, I think since we have `MutationObserver` there is probaby not much point in adding those? (Unless you can come up with some really convincing use case.)

`MutationObserver` is supported since IE11 (so it's not a bleeding edge API), and IE11 is the absolute minimum I would be willing to support. (Not that I'm saying that we currently support IE11, because I haven't tested anything on IE11 in a very long time, so it probably doesn't work; I'm just saying that we can assume that anything IE11 supports we can assume is supported everywhere we'd realistically run.)

**Comment by rickycodes** [comment]
Yea, closing this in favor of keeping the API concise
