### ISSUE TITLE
(question) double unwrapping query_selector

### ISSUE THREAD

**Issue by jaroslaw-weber** [koute/stdweb#220]
I have a question, what is a point of wrapping result of the query_selector into both result and option? I think it would be much nicer to have just one Result.

**Comment by Pauan** [comment]
The outer `Result` is because [the string you use for the selector might have a syntax error (because it's invalid)](https://dom.spec.whatwg.org/#scope-match-a-selectors-string).

The inner `Option` is because [the element might not exist](https://dom.spec.whatwg.org/#dom-parentnode-queryselector).

Because you usually use a string literal, you can guarantee that it doesn't have invalid syntax, so you can safely use `.unwrap()` for the outer `Result`. Though you have to be careful: new CSS syntax might work in a modern browser but fail in an older browser.

On the other hand, the inner `Option` usually needs to be handled, because in many cases you can't guarantee that the element will exist.

**Comment by koute** [comment]
In general the pattern we use is `Result<T, E>` where `T` is the returned type as defined in the specs, and `E` is the exception the method can throw. And since the method can return null it returns `Option<U>` as `T`.

**Comment by jaroslaw-weber** [comment]
Ok i get it now, thanks. 
I didn't see the explanation in the docs and the error is TODO.
