### ISSUE TITLE
Can not use js_serializable! from outside the create

### ISSUE THREAD

**Issue by Pajn** [koute/stdweb#25]
When I try to use `js_serializable!` I get the following error:

```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> src/lib.rs:45:1
   |
45 | js_serializable!(MyType);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ impl doesn't use types inside crate
   |
   = note: the impl does not reference any types defined in this crate
   = note: define and implement a trait or new type instead
   = note: this error originates in a macro outside of the current crate
```

The line is right below the type that I have defined so it should work. I don't know if there's something I can do to get a more precise error message as the macro expands quite a bit it's hare (at least for me) to pinpoint the error.

A bit OT, but I don't know where else to ask. Is it possible to pass values to JS without serializing them?

**Comment by koute** [comment]
Oops!

I could have sworn it worked on an older Rust, but maybe not...? Nevertheless I've fixed it, so it should work properly now; feel free to grab newest `master` and try it out.

Anyway, thanks for the report!

> A bit OT, but I don't know where else to ask. Is it possible to pass values to JS without serializing them?

Some values, yes. Anything complex (e.g. strings, structs, etc.) is out of the question, however if you'd want to pass an array of primitives (e.g. `&[u32]`) with as little overhead as possible then it is doable since JS can access Rust's "memory" as a typed array. (e.g. see `src/webapi/typed_array.rs` for a work-in-progress of such a thing)

**Comment by koute** [comment]
... and also published to crates.io as `0.1.3`.

**Comment by Pajn** [comment]
Seems to work with a quick test. Thanks!

>Some  values, yes. Anything complex (e.g. strings, structs, etc.) is out of  the question, however if you'd want to pass an array of primitives (e.g.  &[u32]) with as little overhead as possible then it is doable since JS can access Rust's "memory" as a typed array. (e.g. see src/webapi/typed_array.rs for a work-in-progress of such a thing)

I read up on emscripten and is far more lower level than I ever thought, kind of obvious in the hindsight but I somehow expected stuff to somehow magically already be JS objects. I will have to reevaluate my strategy a bit.
