### ISSUE TITLE
One question?

### ISSUE THREAD

**Issue by xianghx** [koute/stdweb#260]
Stdweb and wasm-bindgen( web-sys js-sys),

What's the difference?

**Comment by Pauan** [comment]
wasm-bindgen and stdweb are both trying to do the same thing, but they have different philosophies:

1. wasm-bindgen is more "official", since it's heavily promoted by the rustwasm group.

2. wasm-bindgen is missing a lot of useful features compared to stdweb. In my opinion stdweb is very usable, whereas wasm-bindgen is missing too much stuff.

   For example, closures are very well supported by stdweb, but only partially supported by wasm-bindgen.

   Also stdweb has *excellent* support for JS Promises, whereas wasm-bindgen is only just now getting some initial support for them.

3. web-sys is automatically generated from WebIDL. That means that it supports more APIs compared to stdweb, but the APIs are generally a lot worse (stdweb APIs are hand-crafted, so they can be made much higher quality).

4. It's awkward to call custom JS APIs in wasm-bindgen (you have to define a separate `.js` file, which isn't officially supported yet), but it's really easy in stdweb (using the `js!` macro).

5. In general wasm-bindgen takes the approach of making the APIs as close to JS as possible (even if that makes them really awkward to use), whereas stdweb takes the approach of tweaking the APIs to make them fit better with Rust.

In my opinion stdweb is a lot more "production ready" (I'm using it for fairly large and complex 10k+ LOC projects and it works great), whereas wasm-bindgen still has a ways to go.

But wasm-bindgen is improving at a really fast pace, so that will probably change in the near future.

**Comment by xianghx** [comment]
Thank you for your explanation .
