### ISSUE TITLE
SVGElement but not svg tag

### ISSUE THREAD

**Issue by NeverGivinUp** [koute/stdweb#313]
I'm considering implementing some svg api, but my rust and stdweb knowledge is insufficient. Help me out, please.

SVGElement is the interface all elements in the svg namespace implement. It provides functionality similar to the INode interface. Notably the ownerSVGElement function returns an Option of a SVGElement similar to the parentElement function of the Node interface. The return type of parent_element in Stdweb is Option< Element >, though "The parent of an element is an Element node, a Document node, or a DocumentFragment node." ([Source](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentNode#Syntax)). This works, I suppose, because Document and DocumentFragment can, for all practical purposes, be considered the html tag element or another element. In the SVG case this is not possible. The svg tag  element does have attributes some, but not all other elements share. Thus it cannot be considered a super type of all other tags in the svg namespace. So ownerSVGElement cannot return Option<SVGElement> but must return Option<ISVGElement>.

The function owner_svg_element of the trait `ISVGElement: IElement`
```   rust
    fn owner_svg_element(&self) -> Option<ISVGElement> {
        unsafe {
            js!(
                return @{self.as_ref()}.ownerSVGElement;
            ).into_reference_unchecked()
        }
    }
```
errors as follows
``` 
error[E0191]: the value of the associated type `Error` (from the trait `webcore::try_from::TryFrom`) must be specified
  --> src\webapi\svg_element.rs:37:42
   |
28 |     fn owner_svg_element(&self) -> Option<ISVGElement> {
   |                                          ^^^^^^^^^^^ associated type `Error` must be specified
   | 
  ::: src\webcore\try_from.rs:6:5
   |
6  |     type Error;
   |     ----------- `Error` defined here
```
The same for `fn viewport_element(&self) -> Option<ISVGElement>`, which is the more relevant, as not all elements have a viewport, but the svg tag element as well as some other elements do.

If I change the signature to 
```rust
fn owner_svg_element(&self) -> Option<ISVGElement<Error=::stdweb::private::ConversionError>> 
```
the error changes to 
```
error[E0221]: ambiguous associated type `Error` in bounds of `webapi::svg_element::ISVGElement`
  --> src\webapi\svg_element.rs:28:55
   |
28 |     fn owner_svg_element(&self) -> Option<ISVGElement<Error=::stdweb::private::ConversionError>> {
   |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ambiguous associated type `Error`
   | 
  ::: src\webcore\try_from.rs:6:5
   |
6  |     type Error;
   |     -----------
   |     |
   |     ambiguous `Error` from `webcore::try_from::TryFrom<webcore::value::Reference>`
   |     ambiguous `Error` from `webcore::try_from::TryFrom<webcore::value::Value>`
```

**Comment by koute** [comment]
> In the SVG case this is not possible. The svg tag element does have attributes some, but not all other elements share.

Can you give me some examples?

> `fn owner_svg_element(&self) -> Option<ISVGElement> {`

You probably want it to look like this:

```rust
fn owner_svg_element(&self) -> Option<SvgElement> {
    js!(
        return @{self.as_ref()}.ownerSVGElement;
    ).try_into().unwrap()
}
```

where `ISvgElement` and `SvgElement` would be defined as:

```rust
pub trait ISvgElement: IElement {
    // ...
}

#[derive(Clone, Debug, PartialEq, Eq, ReferenceType)]
#[reference(instance_of = "SVGElement")]
#[reference(subclass_of(EventTarget, Node, Element))]
pub struct SvgElement( Reference );

impl IEventTarget for SvgElement {}
impl INode for SvgElement {}
impl IElement for SvgElement {}
impl ISvgElement for SvgElement {}
```

Basically, you're not supposed to return traits.

**Comment by NeverGivinUp** [comment]
> > In the SVG case this is not possible. The svg tag element does have attributes some, but not all other elements share.
> 
> Can you give me some examples?

If you compare elements - for extreme cases see the [svg tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg), the [title tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) and the [discard tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/discard), the only attributes all seem to have in common are the [core attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Core) .

Many elements have more attributes in common: [styling attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Styling), [global event attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Events#Global_Event_Attributes), [presentation attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#Presentation_Attributes) and the [conditional processing attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#Generic_Attributes). Graphics elements additionally have [graphical event attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Events#Graphical_Event_Attributes). 

Most svg elements have element-specific attributes in addition to common groups of attributes. [svg tag-specific attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg#Attributes) are baseProfile, contentScriptType, contentStyleType, height, preserveAspectRatio, version, viewBox, width, x, y. There are other elements that share some of these element-specific attributes. e.g. the [view element ](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/view#Specific_attributes) shares preserveAspectRatio and viewBox.

On a side note: Half of the element-specific attributes of svg element are deprecated. What is stdweb's policy on implementing deprecated and experimental tags and attributes?


> Basically, you're not supposed to return traits.

So the alternatives are as follows
- give all element-specific attributes and attribute groups to all elements in the svg namespace, like in your code fragments above.
- create an AbstractSVGELement that represents the javascript interface as an stdweb struct
- change stdweb's restriction to not return traits (which would be a breaking change)
- others?

**Comment by Pauan** [comment]
@NeverGivinUp The reason you can't return traits isn't because of stdweb, it's a limitation in Rust itself.

Rust is statically typed, so everything ***must*** have a concrete type which is known at compile time.

Even when you use things like `impl Foo` or `Box<dyn Foo>` the Rust compiler must still know the concrete type (so it can convert it into the trait). After it has been converted into a trait, then it no longer needs a concrete type.

So you will need concrete types for the various SVG elements, there is no way around that. As @koute mentioned, it's easy to create such types by using `ReferenceType`, `instance_of`, and `subclass_of`.

Each SVG element should be a distinct struct, using `subclass_of` to establish class inheritance.

However, even though you can use `subclass_of` to create class inheritance, that does not give you *method or property* inheritance, because Rust does not have method/property inheritance.

So instead, in stdweb we use traits to simulate method/property inheritance (though there is [a proposal to replace traits with Deref](https://github.com/koute/stdweb/issues/293), you can ignore that for now).

Basically, you use traits for methods which are shared between many types, and concrete methods for methods which exist only on a specific type.

Let me give an example, so you can clearly see how we do things. You can then use the same techniques for SVG.

1. We create an [`EventTarget` struct](https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/event_target.rs#L83-L85) which is a concrete Rust type used for the [`EventTarget` class in JS](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget).

   It uses `instance_of` to verify at runtime that it is the correct JS class (`EventTarget`).

   Technically it is only needed for it to derive `ReferenceType`, but we also derive other traits such as `Clone`, `Debug`, `PartialEq`, and `Eq`. This makes it more useful for Rust programmers.

2. We create an [`IEventTarget` trait](https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/event_target.rs#L43-L76), which contains all of the `EventTarget` methods. As you can see, it has `add_event_listener` and `dispatch_event`.

   It defines the methods as *default methods*, which means they will be automatically provided on all types which impl `IEventTarget`. This is done for convenience.

3. We create [an impl for `IEventTarget`](https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/event_target.rs#L87). Because we defined the default methods in the trait definition, we do not need to define them here.

That is all that is needed to create a root type (such as `EventTarget`).

Now let's look at how we can create sub-classes of `EventTarget`:

1. We create a [new `Node` struct](https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/node.rs#L358-L361). It is very similar to `EventTarget`, except it uses `reference(subclass_of(EventTarget))` to specify that it is a sub-class of `EventTarget`.

   When a type uses `subclass_of`, it automatically adds in `From` and `TryFrom` implementations, so you can use `foo.into()` and `foo.try_into()` to convert to/from `Node` and `EventTarget`.

   That is all that it does, it does not cause any of the methods to be inherited.

2. We create a [new `INode` trait](https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/node.rs#L28-L345) which contains all of the `Node` methods.

   Notice that the `INode` trait *inherits* from the `IEventTarget` trait. This does not cause the methods to be inherited, instead what it means is: if a type implements `INode`, it must *also* implement `IEventTarget`.

3. We add [impls for `IEventTarget` and `INode`](https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/node.rs#L363-L364).

   Because the `IEventTarget` and `INode` traits use default methods, we don't need to specify the methods here, so it is much more convenient.

   Because we have implemented both `IEventTarget` and `INode`, that means that `Node` contains the methods for both `IEventTarget` and `INode`. This is how we simulate method inheritance.

That's it! As you can see, creating a sub-class is very similar to creating a root class.

Of course we can go deeper as well. Here is how the `Element` class is defined:

1. https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/element.rs#L277-L280

2. https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/element.rs#L24-L269

3. https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/element.rs#L282-L284

It is the same as how we created `Node`.

The end result is:

* Users can use `IEventTarget` methods with `EventTarget`, `Node`, and `Element`.

* Users can use `INode` methods with `Node` and `Element`.

* Users can use `IElement` methods with `Element`.

* Users can use `From` and `TryFrom` to safely convert between `EventTarget`, `Node`, and `Element`.

* We only need to define the methods once, so it avoids code duplication.

* Everything is statically type-safe, so users cannot use `INode` or `IElement` methods with `EventTarget`.

If there are some methods which exist *only* on one specific type, we just use normal inherent methods:

https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/node.rs#L366-L396

As for deprecated methods, we generally don't add them in unless there is a very good reason to do so.

We're more accepting of experimental methods, though it needs to be clear in the documentation where they are supported (and where they're not supported).

Does that answer your questions? Is there anything which is still not clear?

**Comment by Pauan** [comment]
P.S. There are some methods which are defined as *mixins*, so they don't belong to a particular class. In that case we use this technique:

1. First we define the mixin as a standalone trait:

   https://github.com/koute/stdweb/blob/ac9661376e8860d02705b84cf8865e04ae402b06/src/webapi/parent_node.rs#L15-L37

2. For each type which uses the mixin, we add it as a parent to the trait:

   https://github.com/koute/stdweb/blob/85e4e8230b9db5c5ba32989184b0885aad7e0219/src/webapi/element.rs#L24

   Notice how `IElement` inherits from `IParentNode`. This works because Rust traits support *multiple inheritance*, unlike JavaScript which only supports single inheritance.

3. We add an impl so that every `IElement` automatically implements `IParentNode`:

   https://github.com/koute/stdweb/blob/85e4e8230b9db5c5ba32989184b0885aad7e0219/src/webapi/element.rs#L286

**Comment by NeverGivinUp** [comment]
Thank you @Pauan, for the detailed explanation. It has been very helpful. And thank you @Pauan, too. And merry Christmas, to you (if you are christian or just like the festivities).

It seems my confusion mainly stemmed from naively equalizing Javascript interfaces with Rust traits. Instead in StdWeb I need to represent a Javascript Interface it by a Rust struct, which references that Interface. A corresponding trait is purely for the convenient default implementations. It has nothing to do with the Javascript Interface. To represent a Javascript Interface separately from a Javascript Class I need to create separate Rust structs for each of them.

Another confusion of mine was between [SVGElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement) and [SVGSVGElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement). The former is the Javascript Interface from which all SVG elements inherit. The latter is the Javascript Interface to the svg tag element. I'm obviously a rookie, when it comes to modern web development.

Most developers that currently use StdWeb have a solid Javascript and WebApi background. In time more developers will use StdWeb, that are not as familiar with them. Suppose they try to instantiate of SVGElement or HTMLElement. What is the idiomatic way to tell them to use SVGSVGElement or HTMLHtmlElement instead? Documentation? An explicit check (and error) in  document().create_element() and document().create_element_ns()?

**Comment by Pauan** [comment]
> @NeverGivinUp And merry Christmas, to you

Yeah, you too.

> It seems my confusion mainly stemmed from naively equalizing Javascript interfaces with Rust traits.

WebIDL interfaces are actually the same as JavaScript classes (i.e. concrete types). They're not interfaces at all (even though they're called interfaces).

WebIDL mixins are more like interfaces (and they map cleanly to Rust traits). Yes, it's confusing.

> A corresponding trait is purely for the convenient default implementations. It has nothing to do with the Javascript Interface.

Yes, though it's more precise to say that the Rust struct corresponds to the JavaScript class while the Rust trait corresponds to the JavaScript methods.

The other reason is to allow for method/property inheritance (e.g. you can create a method which accepts `IElement` and it will then work with many different types).

> To represent a Javascript Interface separately from a Javascript Class I need to create separate Rust structs for each of them.

Yes, each interface corresponds to a separate Rust struct.

Except a WebIDL interface is the same as a JavaScript class, they're not separate things. So a Rust struct corresponds to a JavaScript class (which is the same as a WebIDL interface).

> Another confusion of mine was between SVGElement and SVGSVGElement. The former is the Javascript Interface from which all SVG elements inherit. The latter is the Javascript Interface to the svg tag element.

Yes, it's quite confusing. As you figured out, `SVGElement` is a generic class for all SVG elements, and `SVGSVGElement` is specifically for the `<svg>` tag.

> I'm obviously a rookie, when it comes to modern web development.

That's not a problem, we can help fill in any missing gaps and answer questions.

> Suppose they try to instantiate of SVGElement or HTMLElement. What is the idiomatic way to tell them to use SVGSVGElement or HTMLHtmlElement instead? Documentation? An explicit check (and error) in document().create_element() and document().create_element_ns()?

This is done using `TryInto`, like this:

```rust
let x: InputElement = document().create_element("input").unwrap().try_into().unwrap();
```

Or for SVG elements:

```rust
let x: SvgPathElement = document().create_element_ns("http://www.w3.org/2000/svg", "path").unwrap().try_into().unwrap();
```

The type (`InputElement` or `SvgPathElement`) must match the tag (`input` or `path`).

I recommend creating helper functions to make the above easier:

```rust
fn create_element<A>(tag: &str) -> A where A: TryFrom<Element> {
    document().create_element(tag).unwrap().try_into().unwrap()
}
```

```rust
let x: InputElement = create_element("input");
```

Or perhaps using a DOM framework like [dominator](https://crates.io/crates/dominator).

There's actually [quite a few DOM frameworks available](https://crates.io/search?q=dom) for Rust (including Virtual DOM ones like [yew](https://crates.io/crates/yew))

**Comment by Pauan** [comment]
Oh, I just now realized I didn't really answer your question.

> Suppose they try to instantiate of SVGElement or HTMLElement. What is the idiomatic way to tell them to use SVGSVGElement or HTMLHtmlElement instead? Documentation? An explicit check (and error) in document().create_element() and document().create_element_ns()?

Since the JavaScript runtime class is determined by the tag (not the type), it is perfectly valid to create an `SvgElement` from an `svg` tag.

It won't give an error, but of course you'll only be able to use the `SvgElement` methods (if you try to use an `SvgSvgElement` method it will give you a compile error).

If you want to use `SvgSvgElement` methods, all you have to do is change the type to `SvgSvgElement` (the tag can stay the same).

Maybe we could use some documentation for that.

Or perhaps instead we could create something similar to `ConcreteEvent`, and make it impossible to mess up:

```rust
let x: SvgSvgElement = document().create_element().unwrap();
```

I like that idea a lot. I should implement that in dominator.

**Comment by NeverGivinUp** [comment]
Thanks again @Pauan! I managed to get a stub implementation of SVGSVGElement working. 

When I create it like this (I am aware, that in practice I'll need something like a namespace handle and can't just write an attribute):
```
    let svg_element: SVGSVGElement = document().create_element_ns("http://www.w3.org/2000/svg", "svg").unwrap().try_into().unwrap();
    svg_element.set_attribute("xmlns:xlink", "http://www.w3.org/1999/xlink").unwrap();
```
I get
```
<svg xmlns:xlink="http://www.w3.org/1999/xlink"></svg>
```
The xlink namespace, i added manually, is there. The svg namespace is missing.

Do you happen to know if this is 
- me using create_element_ns in a wrong way
- intended behaviour, as the svg namespace is known in the browser
- a bug in create_element_ns

**Comment by Pauan** [comment]
@NeverGivinUp In the browser debugger tools it doesn't show the namespace, but it really is there.

You can verify this by selecting the `<svg>` tag, and then running `$0.namespaceURI` in the console.

**Comment by NeverGivinUp** [comment]
I'm just going to believe you. Thanks @koute !
