### ISSUE TITLE
Export emscripten_set_main_loop()

### ISSUE THREAD

**Issue by ndarilek** [koute/stdweb#48]
I'm trying to use a modified version of [this guide](https://blog.fazibear.me/definitive-guide-to-rust-sdl-2-and-emscripten-93d707b22bbb) to run an SDL app. Looks like I'm hitting the condition where SDL's event loop blocks the entire browser, so I need to tell emscripten about it.

It looks like you define this function in the crate, but it is private. Any reason it isn't exported? Is there currently an alternative way of getting at this functionality?

Note that I'm pretty new to all of this, so I don't really understand the requirements beyond suspecting that SDL's and Emxcripten's main loops don't play well together, I suppose. :)

Thanks.

**Comment by koute** [comment]
I don't export it since I don't really want to expose Emscripten itself through `stdweb`; the idea is that everything inside of `stdweb` should work on every backend. I *might* add something in the future which would abstract over Emscripten's main loop, but for now I'm not yet sure how that would look like.

If you want to use Emscripten specific stuff in your program you can simply import it yourself for now:

```rust
pub type CallbackFn = Option< unsafe extern "C" fn() >;

extern "C" {
    fn emscripten_pause_main_loop();
    fn emscripten_set_main_loop( callback: CallbackFn, fps: i32, simulate_infinite_loop: i32 );
}
```

**Comment by koute** [comment]
Since this is out-of-scope for `stdweb` - closing.
