### ISSUE TITLE
Run web API tests on CI and provide instructions for running locally

### ISSUE THREAD

**Issue by Diggsey** [koute/stdweb#59]
I have no idea how to run them locally and the CI script passes `--nodejs` which doesn't support them anyway!

How difficult would it be to support something like http://zombie.js.org/ or just headless chrome?

**Comment by koute** [comment]
You just don't pass `--nodejs` and then `cargo-web` will try to run them in Chrome/Chromium. (You also need to temporairly comment the `#[cfg(...)]` which prevents them from running, since I haven't yet implemented support for switch on features in `cargo-web`.)

Right now it's very hacky which is why it's not done on the CI. In the future I would certainly want to switch to headless Chrome or Firefox, *then* we can start running them on CI.

As to how hard would it be to support headless Chrome? Well, quite frankly I'm not sure. We'd have to implement the [devtools protocol](https://chromedevtools.github.io/devtools-protocol/) to communicate with it, and we'd have to get precompiled binaries for it from *somewhere* - probably build them ourselves just as we do for Emscripten (this alone is a huge pain since compiling Chrome takes **ages**, and the build system is a nightmare to set up).

**Comment by RangerMauve** [comment]
What about using an existing node.js headless chrome and creating WASM bindings for it?

**Comment by koute** [comment]
All of the tests are being run on CI and I've added instructions on how to run them at the end of the README, so closing.
