### ISSUE TITLE
Chrome / Firefox Extension APIs

### ISSUE THREAD

**Issue by Pauan** [koute/stdweb#71]
There are [Chrome](https://developer.chrome.com/extensions/api_index) and [Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) extension APIs which I would like to use.

Should they be added to this repo, or to a separate repo? If it's okay to add them to this repo, then I'll send some pull requests implementing them. I have a lot of experience using those APIs, so I know how to work around some bugs/quirks in them.

However, almost all of the extension APIs are asynchronous, so stdweb will need good Promise support first.

Also, ideally we should be able to write extensions that can work on either Chrome or Firefox. That could be accomplished either with runtime polyfills, or with conditional compilation within Rust.

**Comment by koute** [comment]
You want to write browser extensions in Rust? That's... certainly an interesting idea!

I think that would be out of scope of `stdweb` itself and would be more appropriate to have in a separate crate. I would be of course willing to get `stdweb` itself up to snuff so that actually having such functionality in a separate crate would be feasible. (As I don't really know browser extension APIs it's hard for me to tell.)

**Comment by Pauan** [comment]
@koute That's reasonable. For now, the biggest blocker is lack of good Promise support. I filed a new issue https://github.com/koute/stdweb/issues/72

**Comment by amaury1093** [comment]
@Pauan Did you ever get started on writing WebExtensions API for stdweb?

Edit: For future people, I found this https://github.com/rustwasm/gloo/issues/21

**Comment by Pauan** [comment]
@amaurymartiny I've completely moved to wasm-bindgen. I have some [WebExtensions APIs created](https://github.com/Pauan/tab-organizer/tree/d89b1318b7b4084e5a1b0172ab999d14ef86bc36/web-extension), but they're not published yet.
