### ISSUE TITLE
Some WebGL objects cannot put in the weakmap in firefox

### ISSUE THREAD

**Issue by edwin0cheng** [koute/stdweb#92]
I am trying to using WebGL in rust by stdweb, however, i found that
some WebGL related objects (WebGLBuffer, WebGLUniformLocation, etcs) could not put in the WeakMap in firefox (Chrome do not have this problem).
 
Do you think there are any alternative solutions instead of current WeakMap implementation ?

**Comment by koute** [comment]
That's... interesting. Hmm... possibly.

Have you tried to see how Emscripten's OpenGL emulation layer handles this?

**Comment by edwin0cheng** [comment]
Just checked, basically, emscripten WebGL Client use a big object table to store  all objects :

https://github.com/kripken/emscripten/blob/7f89560101843198787530731f40a65288f6f15f/src/webGLClient.js

You can search "getUniformLocation" and "uniform4fv" to understand how it works...
Maybe i would need to do something like these by myself.  T T

**Comment by edwin0cheng** [comment]
Oh seem like you mis-understand what i say.

When using js! macro to return an object to rust side, stdweb are using WeakMap to store the object.
However, firefox is not allowed to store these objects in WeakMap, so stdweb should fail at that point.

**Comment by Diggsey** [comment]
AIUI, the only reason we need a weak map is to ensure that if the same object is exposed to rust multiple times, it gets the same ID each time - could we just drop that guarantee? (Use a strong map and remove items when their refcount goes to zero)

**Comment by edwin0cheng** [comment]
As i understand, use a strong map should have the same ID each time too.  
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), Object as keys are considered equal according to the semantics of the === operator which is only equal compare to itself.

And Maybe we do not need a WeakMap here as we have keep track the refcount itself? Do i misunderstand something?

**Comment by Diggsey** [comment]
@edwin0cheng yes, the point of using the weak map is so that items stay in the *weak* map even after their reference count reaches zero, as long as the object is still in use by javascript.

If we switch to a strong map, then to avoid memory leaks we would have to remove it form the strong map when the reference count reaches zero: that means that if the object is kept alive on the javascript side, and then passed into rust again at a later time, the later use will receive a different ID.

**Comment by edwin0cheng** [comment]
Oh... you are right, seem like i totally misunderstand that part.

But when the reference count reaches zero, the lifetime of reference object in rust should be end, so that different ID should be okay (as there are no way to interact with the old reference in rust), right ?

**Comment by Diggsey** [comment]
It could break certain use-cases where you wanted a stable ID on the rust side to know whether you see the same object without having to keep it alive.

However, stdweb could provide an explicit "weak reference"/"stable ID" API to allow you to do this (which would then fail for WebGL objects).

**Comment by kuviman** [comment]
@Diggsey Hello, I was looking at the source code, and it looks like objects [are actually removed](https://github.com/koute/stdweb/blob/85f7aa484f3be9808b992b9258bd85fa588e05b1/src/webcore/runtime.js#L332) from the WeakMap when reference count reaches zero.

So I wanted to test if this means that different ID would be generated with this code:
```rust
#[macro_use]
extern crate stdweb;

#[test]
fn test() {
    js! { Module.test = {}; }
    let a = js! { return Module.test; }.as_reference().unwrap().as_raw();
    let b = js! { return Module.test; }.as_reference().unwrap().as_raw();
    assert_eq!(a, b);
}
```

But, the test has passed. Then I looked at the `Module.STDWEB_PRIVATE.id_to_refcount_map`, and it had refcount equal to `2` after this code.

Next, code like this leaves refcount equal to `100`:
```rust
fn main() {
    js! { Module.test = {}; }
    for _ in 0..100 {
        js! { return Module.test; }
    }
}
```

So refcount is initially set to `1` in [`acquire_rust_reference`](https://github.com/koute/stdweb/blob/85f7aa484f3be9808b992b9258bd85fa588e05b1/src/webcore/runtime.js#L308), and incremented [when constructing](https://github.com/koute/stdweb/blob/573c7ce5894087c81170bd1eca2a4a5ead8f2d15/src/webcore/value.rs#L33) a `Reference`, but only decremented once [while dropping](https://github.com/koute/stdweb/blob/573c7ce5894087c81170bd1eca2a4a5ead8f2d15/src/webcore/value.rs#L83) the `Reference`

I believe there are two bugs here - leaking JS objects because of incorrent ref counting, and removing objects from the weak map, which, in case of fixed memory leak would cause different IDs for same objects.

Am I missing something?

**Comment by Diggsey** [comment]
@kuviman nope, looks like you've  found a bug - cc @koute

**Comment by kuviman** [comment]
@Diggsey Ok then, I've created a separate issue since it's not directly related to this once

**Comment by zombiezen** [comment]
FWIW, there is an upstream Firefox bug for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1428438
